# version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    container_name: translation-bot
    hostname: translation-bot
    # restart: always
    environment:
      - PORT=${PORT}
      - TZ=Asia/Taipei
    command: sh -c "python main.py"

    volumes:
      - ../src:/code
    ports:
      - "${PORT}:${PORT}"